### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by BastelPichi**
Complete rewrite.
Removed flask_restful as its not needed.
Should be compatible, only changed apinfo to apiinfo.

@IdotMaster1 Notes for you:
Changes variables for username and password
Change back to custom rpc port
Use proper WSGI server (e.g. Apache or NGINX)

### CODE REVIEW

**Comment by IdotMaster1** [comment]
WSGI is handled by waitress

**Comment by BastelPichi** [comment]
> WSGI is handled by waitress

I know, but a "proper" wsgi serer is better. Performance and secuirty wise. Removed the waitress. Thats why I added that in comments.

**Comment by IdotMaster1** [comment]
> > WSGI is handled by waitress
> 
> I know, but a "proper" wsgi serer is better. Performance and secuirty wise. Removed the waitress. Thats why I added that in comments.

Lazy + Ratio + Im adding waitress back + stay mad

**Comment by IdotMaster1** [comment]
Im gonna test it, brb

**Comment by IdotMaster1** [comment]
I approve 😸

**Pull request merged**
