### PR TITLE
Minor API changes

### PR DESCRIPTION
**Pull request by babymu5k**
just some changes like when you hover over the link it goes black instead of white

### CODE REVIEW

**Comment by BastelPichi** [comment]
Bruh

**Comment by BastelPichi** [comment]
You like undid every peace of beautiful code lol

**Comment by BastelPichi** [comment]
And its not a rest api lol

**Comment by BastelPichi** [comment]
Also spaces are veeeeeeeeeeeeeeeeery bad

**Comment by babymu5k** [comment]
just use html sir

**Comment by BastelPichi** [comment]
And changing minor names breaks alot

**Comment by BastelPichi** [comment]
Ill look into this tmrw

**Comment by BastelPichi** [comment]
> just use html sir

AHYES and then use selenum to scrape the content right?

**Comment by babymu5k** [comment]
ok

**Comment by babymu5k** [comment]
....

**Comment by babymu5k** [comment]
# i meant replace the html files

**Comment by babymu5k** [comment]
### some of the documentation was wrong

**Comment by BastelPichi** [comment]
So you just updated html?
Then, please close this Requests, fork the latest version of this Repo and just change the html.

**Pull request closed without merging**
